In [22]:
# pip install faiss-cpu

In [23]:
import faiss
from langchain_text_splitters import RecursiveCharacterTextSplitter
from sentence_transformers import SentenceTransformer

In [24]:
data=open('data.txt',encoding='utf-8').read()
data

'Artificial Intelligence@ (AI) is one of the fastest-growing fields in technology. It enables machines to simulate human intelligence and solve complex problems. AI includes several domains such as Machine Learning, Deep Learning, Natural Language Processing, and Computer Vision.\n\nMachine Learning allows computers$ to learn from historical data and make predictions. It can be divided into supervised learning, unsupervised learning, and reinforcement learning. Supervised learning uses labeled data🥱, while unsupervised learning finds hidden patterns in unlabeled data.\n\nDeep Learning is based on artificial neural! networks. It has revolutionized image recognition, speech processing, and language translation. Popular frameworks for Deep Learning include TensorFlow and PyTorch.😎😎\n\nNatural Language Processing (NLP) enables computers to understand and generate human language. NLP applications include chatbots, sentiment analysis, machine translation, and text summarization. Tokenization

In [25]:
splitter=RecursiveCharacterTextSplitter(
    chunk_size=100,
    chunk_overlap=20
)
chunks=splitter.split_text(data)

In [26]:
embedding_model=SentenceTransformer(
    model_name_or_path='sentence-transformers/all-miniLM-L6-V2'
)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3064.10it/s]


In [27]:
embeddings=embedding_model.encode(chunks).astype('float32')

In [28]:
embeddings

array([[-0.02008874, -0.02765671, -0.01694681, ...,  0.01775062,
         0.06919765, -0.00531558],
       [-0.04587054, -0.00607229,  0.02830237, ...,  0.09470588,
         0.0457815 , -0.06788609],
       [ 0.01297892, -0.11729943,  0.02437208, ...,  0.05398414,
         0.07589752, -0.03379875],
       ...,
       [-0.02700112,  0.0142837 ,  0.01361219, ...,  0.03451857,
         0.021033  , -0.04701881],
       [ 0.03133938,  0.0220446 ,  0.0349706 , ..., -0.02214807,
        -0.03062211, -0.01050194],
       [ 0.00889864, -0.06766716,  0.01689922, ...,  0.01894414,
         0.00194135,  0.02388038]], shape=(903, 384), dtype=float32)

In [29]:
dimension=embeddings.shape[1]
dimension

384

In [30]:
faiss.normalize_L2(embeddings)

In [31]:
index=faiss.IndexFlatIP(dimension)   #dot product


In [32]:
index.add(embeddings)

# Search Method(R)

In [ ]:
Query='Explain Machine Learning?'

In [55]:
query_embeddings=embedding_model.encode(Query).astype('float32')

In [56]:
query_embeddings=query_embeddings.reshape(1,-1)

In [57]:
query_embeddings

array([[-1.24870595e-02, -2.93795019e-02,  3.04285735e-02,
         1.55043956e-02,  5.17589003e-02, -3.45746949e-02,
        -3.30067682e-03, -2.68255901e-02, -2.55472250e-02,
        -1.16211120e-02, -6.04345538e-02,  3.57629023e-02,
         4.54587452e-02, -8.03952143e-02, -8.29185992e-02,
        -7.45702954e-03, -3.19554396e-02,  2.52577290e-02,
        -9.97760147e-02, -1.09578460e-01,  5.82825616e-02,
        -3.63752767e-02, -6.94946498e-02,  2.50929911e-02,
         2.06710622e-02,  5.07701784e-02,  3.87980677e-02,
         6.04338646e-02,  1.48697104e-02, -9.96481813e-03,
         2.40478162e-02, -1.68943964e-02,  4.03817780e-02,
         3.85296196e-02, -8.52659345e-02,  2.62187868e-02,
        -4.54908274e-02,  4.75514829e-02,  1.19168768e-02,
         5.42534739e-02, -4.02193740e-02, -5.95136322e-02,
        -5.54294325e-03,  2.07224544e-02,  1.39104217e-01,
         8.75249282e-02, -3.82023007e-02, -6.54589906e-02,
        -1.47253703e-02, -5.12091182e-02, -1.56483665e-0

In [60]:

''' 1st value -> distance
    2nd value -> index
    '''
index.search(query_embeddings,k=4)

(array([[0.6688809 , 0.582605  , 0.51393116, 0.5017324 ]], dtype=float32),
 array([[4, 5, 2, 1]]))